const $=s=>document.querySelector(s);let design,published,defaults,dirty=false;
const groups=[['Logo',[['logo','Logo','image'],['logoWidth','Ancho del logo','range',60,240]]],['Banner',[['bannerVisible','Mostrar banner','checkbox'],['bannerImage','Imagen del banner','image'],['bannerEyebrow','Texto superior'],['bannerTitle','Título (vacío: usar nombre de marca)'],['bannerText','Subtítulo (vacío: usar texto de marca)','textarea'],['bannerButton','Texto del botón']]],['Colores',[['paper','Fondo general','color'],['ivory','Fondo del banner','color'],['ink','Texto','color'],['sage','Botones y acentos','color'],['headerColor','Fondo del encabezado','color'],['footerColor','Fondo del footer','color'],['footerTextColor','Texto del footer','color']]],['Tipografía y botones',[['headingFont','Títulos','font'],['bodyFont','Texto','font'],['buttonRadius','Redondeo de botones','range',0,40]]],['Nuestra esencia',[['storyVisible','Mostrar sección','checkbox'],['storyTitle','Título'],['storyText','Texto','textarea']]],['Footer y redes',[['footerVisible','Mostrar footer','checkbox'],['footerLogo','Logo o sello','image'],['footerText','Texto del footer','textarea'],['instagram','Instagram (vacío: usar Sheets)'],['whatsapp','WhatsApp (vacío: usar Sheets)'],['email','Email (vacío: usar Sheets)']]]];
const fonts=['Italiana','DM Sans','Georgia','Arial','Playfair Display','Lora','Montserrat','Nunito'];
async function api(body){const r=await fetch('/api/design',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function error(e){$('#error').textContent=e.message||e;}
function preview(){if(design)$('#preview').contentWindow.postMessage({type:'nawi-design',design},location.origin);}
function changed(){dirty=true;$('#status').textContent='Cambios sin guardar';$('#error').textContent='';preview();}
function render(){const form=$('#fields');form.replaceChildren();for(const [title,fields] of groups){const section=document.createElement('details');section.open=title==='Logo';const summary=document.createElement('summary');summary.textContent=title;section.append(summary);for(const [key,label,type='text',min,max] of fields){const l=document.createElement('label');l.append(document.createTextNode(label));let el;
 if(type==='image'){el=document.createElement('input');el.type='file';el.accept='image/png,image/jpeg,image/webp';const img=document.createElement('img');img.className='image-preview';img.alt=label;img.hidden=!design[key];if(design[key])img.src=design[key];l.append(img);const hint=document.createElement('p');hint.className='hint';hint.textContent='PNG, JPG o WebP · hasta 2 MB';l.append(hint);const remove=document.createElement('button');remove.type='button';remove.textContent='Quitar imagen';remove.onclick=()=>{design[key]='';img.hidden=true;el.value='';changed();};l.append(remove);
 el.onchange=async()=>{const file=el.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('La imagen debe pesar menos de 2 MB.');el.disabled=true;$('#status').textContent='Subiendo imagen…';const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const r=await fetch('/api/design-image',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({data})});const d=await r.json();if(!r.ok)throw Error(d.error);design[key]=d.url;img.src=d.url;img.hidden=false;changed();}catch(e){error(e);}finally{el.disabled=false;}};
 }else if(type==='font'){el=document.createElement('select');fonts.forEach(f=>el.add(new Option(f,f)));el.value=design[key];}
 else if(type==='textarea'){el=document.createElement('textarea');el.value=design[key];}
 else {el=document.createElement('input');el.type=type;if(type==='checkbox')el.checked=design[key];else el.value=design[key];if(type==='range'){el.min=min;el.max=max;}}
 if(type!=='image')el.oninput=()=>{design[key]=type==='checkbox'?el.checked:type==='range'?Number(el.value):el.value;changed();};l.append(el);section.append(l);}form.append(section);}preview();}
async function load(){const r=await fetch('/api/design?admin=1',{cache:'no-store'});if(r.status===401)return;const d=await r.json();if(!r.ok)throw Error(d.error);defaults=d.defaults;published={...defaults,...d.published};design={...defaults,...(d.draft||d.published)};$('#login').hidden=true;$('#editor').hidden=false;$('#logout').hidden=false;$('#status').textContent='Diseño listo para editar';render();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await api({action:'login',password:$('#password').value});$('#password').value='';$('#error').textContent='';await load();}catch(e){error(e);}};
$('#preview').onload=preview;$('#fields').onsubmit=e=>e.preventDefault();$('#mobile').onclick=()=>{$('#frameWrap').style.maxWidth='390px';};$('#desktop').onclick=()=>{$('#frameWrap').style.maxWidth='none';};
async function save(action){const buttons=[...document.querySelectorAll('.savebar button')];buttons.forEach(b=>b.disabled=true);try{await api({action,design});if(action==='publish'){published={...design};await api({action:'draft',design});}dirty=false;$('#status').textContent=action==='publish'?'Cambios publicados en la tienda':'Borrador guardado';$('#error').textContent='';}catch(e){error(e);}finally{buttons.forEach(b=>b.disabled=false);}}
$('#draft').onclick=()=>save('draft');$('#publish').onclick=()=>save('publish');$('#restore').onclick=()=>{design={...published};render();changed();};$('#logout').onclick=async()=>{try{await api({action:'logout'});location.reload();}catch(e){error(e);}};window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});load().catch(error);
